# Generated by Django 5.2 on 2025-04-28 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, help_text='Use o formato (99) 99999-9999.', max_length=15, validators=[django.core.validators.RegexValidator(message='Número de telefone inválido. Use o formato (99) 99999-9999.', regex='^\\(?\\d{2}\\)?\\s?\\d{4,5}-?\\d{4}$')])),
                ('active', models.BooleanField(db_default=True)),
            ],
        ),
    ]
